// Generates SQL + JSON exports of the vocabulary bank from the canonical TS
// seed files, so the same data drives both the local app and Supabase.
//
// Usage:  node scripts/export-vocab.mjs
// Writes: supabase/seed_vocabulary.sql, supabase/vocabulary.json

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const LEVELS = ["B1", "B2", "C1", "C2"];

/** Pull the array literal out of a per-level .ts file and eval it as JS. */
function readLevel(level) {
  const file = join(root, "src", "data", "words", `${level.toLowerCase()}.ts`);
  const text = readFileSync(file, "utf8");
  const marker = "RawWord[] =";
  const after = text.slice(text.indexOf(marker) + marker.length);
  const arrText = after.slice(after.indexOf("["), after.lastIndexOf("]") + 1);
  // Trusted, local build-time input.
  return eval(`(${arrText})`);
}

function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

function sqlArray(arr) {
  if (!arr || arr.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${arr.map(sqlStr).join(",")}]`;
}

function sqlJson(obj) {
  if (!obj) return "NULL";
  return `${sqlStr(JSON.stringify(obj))}::jsonb`;
}

const all = [];
for (const level of LEVELS) {
  const raws = readLevel(level);
  raws.forEach((r, i) => {
    all.push({
      id: `${level.toLowerCase()}-${String(i + 1).padStart(3, "0")}`,
      languageCode: "es",
      word: r.word,
      definition: r.definition,
      exampleSentence: r.example,
      cefrLevel: level,
      category: r.category,
      synonyms: r.synonyms ?? [],
      usage: r.usage ?? null,
    });
  });
}

// --- SQL ---
const rows = all
  .map(
    (w) =>
      `(${sqlStr(w.id)}, 'es', ${sqlStr(w.word)}, ${sqlStr(w.definition)}, ${sqlStr(
        w.exampleSentence,
      )}, ${sqlStr(w.cefrLevel)}::cefr_level, ${sqlStr(w.category)}, ${sqlArray(w.synonyms)}, ${sqlJson(
        w.usage,
      )})`,
  )
  .join(",\n");

const sql = `-- Auto-generated by scripts/export-vocab.mjs — do not edit by hand.
-- ${all.length} Spanish vocabulary words across B1/B2/C1/C2.

insert into public.vocabulary_words
  (id, language_code, word, definition, example_sentence, cefr_level, category, synonyms, usage)
values
${rows}
on conflict (id) do update set
  word = excluded.word,
  definition = excluded.definition,
  example_sentence = excluded.example_sentence,
  cefr_level = excluded.cefr_level,
  category = excluded.category,
  synonyms = excluded.synonyms,
  usage = excluded.usage;
`;

mkdirSync(join(root, "supabase"), { recursive: true });
writeFileSync(join(root, "supabase", "seed_vocabulary.sql"), sql, "utf8");
writeFileSync(join(root, "supabase", "vocabulary.json"), JSON.stringify(all, null, 2), "utf8");

console.log(`Exported ${all.length} words → supabase/seed_vocabulary.sql + vocabulary.json`);
